package views;

import javax.swing.*;
import controllers.*;
import java.awt.Font;
import models.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tomas
 */
public class CustomerWindow extends javax.swing.JFrame {
    
    private InitialData initialData = new InitialData();
    private OrderModel order;
    
    /**
     * Creates new form CustomerWindow
     */
    public CustomerWindow(OrderModel order) {    
        this.order = order;
        initComponents();
        
        lblValueCustomerId.setText(order.getCustomerId());
        lblValueCustomerName.setText(order.getCustomerName());
        
        tblMenu.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblMenu.getTableHeader().setOpaque(false);
        tblMenu.getTableHeader().setForeground(new java.awt.Color(220, 60, 44));
        tblMenu.setRowHeight(40);
        
        cbxMenusList.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        lblMenuIcon = new javax.swing.JLabel();
        lblSelectMenu = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        lblValueCustomerName = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cbxMenusList = new javax.swing.JComboBox<>();
        lblValueCustomerId = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        lblMenu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblPrice = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblNameItem = new javax.swing.JLabel();
        btnFinishOrder = new javax.swing.JLabel();
        btnAddOrderItem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(46, 61, 79));

        lblMenuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_icon.png"))); // NOI18N

        lblSelectMenu.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblSelectMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSelectMenu.setText("Selección Menú");

        lblCustomerId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCustomerId.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCustomerId.setText("No. de Identificación");

        lblValueCustomerName.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblValueCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        lblValueCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblCustomerName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCustomerName.setText("Nombre");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        cbxMenusList.setBackground(new java.awt.Color(254, 244, 236));
        cbxMenusList.setForeground(new java.awt.Color(46, 61, 79));
        cbxMenusList.setModel(new DefaultComboBoxModel(initialData.getMenus().toArray()));
        cbxMenusList.setBorder(null);
        cbxMenusList.setOpaque(false);
        ChangeEvent changeEvent = new ChangeEvent(this);
        cbxMenusList.addActionListener(changeEvent);

        lblValueCustomerId.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblValueCustomerId.setForeground(new java.awt.Color(255, 255, 255));
        lblValueCustomerId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sidePanelLayout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(lblMenuIcon))
                        .addGroup(sidePanelLayout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValueCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxMenusList, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(sidePanelLayout.createSequentialGroup()
                                    .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(104, 104, 104))))
                        .addGroup(sidePanelLayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(lblSelectMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValueCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(jSeparator1)))
                        .addGap(10, 10, 10)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSelectMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxMenusList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblCustomerId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValueCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblCustomerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValueCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(238, 235, 193));
        contentPanel.setForeground(new java.awt.Color(30, 214, 214));

        jScrollPane1.setBackground(new java.awt.Color(238, 235, 193));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(238, 235, 193));
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tblMenu.setBackground(new java.awt.Color(238, 235, 193));
        tblMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tblMenu.setForeground(new java.awt.Color(46, 61, 79));
        tblMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMenu.setFocusable(false);
        tblMenu.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblMenu.setRowHeight(25);
        tblMenu.setShowHorizontalLines(false);
        tblMenu.setShowVerticalLines(false);
        tblMenu.getTableHeader().setReorderingAllowed(false);
        tblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenu);

        lblMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(46, 61, 79));

        jPanel2.setBackground(new java.awt.Color(238, 235, 193));

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(220, 60, 44));

        jScrollPane2.setBorder(null);

        txtDescription.setEditable(false);
        txtDescription.setBackground(new java.awt.Color(238, 235, 193));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(220, 60, 44));
        txtDescription.setRows(5);
        txtDescription.setBorder(null);
        jScrollPane2.setViewportView(txtDescription);

        lblNameItem.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblNameItem.setForeground(new java.awt.Color(220, 60, 44));

        btnFinishOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFinishOrder.setForeground(new java.awt.Color(238, 136, 67));
        btnFinishOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFinishOrder.setText("Terminar Orden");
        btnFinishOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 136, 67), 3));
        btnFinishOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinishOrder.addMouseListener(new CustomerClickEvent(this));

        btnAddOrderItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAddOrderItem.setForeground(new java.awt.Color(238, 136, 67));
        btnAddOrderItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddOrderItem.setText("Agregar a la Orden");
        btnAddOrderItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 136, 67), 3));
        btnAddOrderItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddOrderItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddOrderItemMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddOrderItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnFinishOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblNameItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAddOrderItem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinishOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1134, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenuMouseClicked
        int selectedRow = tblMenu.getSelectedRow();
        FoodModel item = initialData.getMenus().get(cbxMenusList.getSelectedIndex()).getItems().get(selectedRow);
        
        lblNameItem.setText(item.getName());
        txtDescription.setText(item.getDescription());
        lblPrice.setText("$ " + String.valueOf(item.getPrice()));
    }//GEN-LAST:event_tblMenuMouseClicked

    private void btnAddOrderItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddOrderItemMouseClicked
        int selectedRow = tblMenu.getSelectedRow();
        FoodModel item = initialData.getMenus().get(cbxMenusList.getSelectedIndex()).getItems().get(selectedRow);
        
        order.addItem(item);
        JOptionPane.showMessageDialog(null, "Se agregó " + item.getName() + " exitosamente a la orden.");
    }//GEN-LAST:event_btnAddOrderItemMouseClicked

    public JLabel getLblValueCustomerId() {
        return lblValueCustomerId;
    }

    public JLabel getLblValueCustomerName() {
        return lblValueCustomerName;
    }

    public JLabel getBtnFinishOrder() {
        return btnFinishOrder;
    }

    
    /**
     * @param menu el menu para mostrar en la tabla
     */
    public void setContentMenu(MenuModel menu) {
        lblMenu.setText(menu.getName());
        
        String[] headers = {"Nombre", "Precio"};
        tblMenu.removeAll();
        
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers); 
        tblMenu.setModel(tableModel);
        
        menu.getItems().forEach((item)->{
            tableModel.addRow(item.toArray());
        });        
    }

    public JComboBox<String> getCbxMenusList() {
        return cbxMenusList;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddOrderItem;
    private javax.swing.JLabel btnFinishOrder;
    private javax.swing.JComboBox<String> cbxMenusList;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMenuIcon;
    private javax.swing.JLabel lblNameItem;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSelectMenu;
    private javax.swing.JLabel lblValueCustomerId;
    private javax.swing.JLabel lblValueCustomerName;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTextArea txtDescription;
    // End of variables declaration//GEN-END:variables
}
