package views;

import java.awt.*;
import javax.swing.*;
import controllers.MainClickEvent;

/**
 *
 * @author tomas
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        lblStaffIcon = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        btnStaffLogin = new javax.swing.JPanel();
        lblStaffLogin = new javax.swing.JLabel();
        txtStaffPassword = new javax.swing.JPasswordField();
        lblStaffPassword = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        customerPanel = new javax.swing.JPanel();
        lblCustomerIcon = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        btnMakeOrder = new javax.swing.JPanel();
        lblMakeOrder = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        txtCustomerId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblCustomerName = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante");
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/icon.png"));
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        adminPanel.setBackground(new java.awt.Color(241, 211, 142));

        lblStaffIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_icon.png"))); // NOI18N

        lblAdmin.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(46, 61, 79));
        lblAdmin.setText("Personal");

        btnStaffLogin.setBackground(new java.awt.Color(241, 211, 142));
        btnStaffLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 60, 44), 3));
        btnStaffLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStaffLogin.addMouseListener(new MainClickEvent(this));

        lblStaffLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblStaffLogin.setForeground(new java.awt.Color(220, 60, 44));
        lblStaffLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStaffLogin.setText("Ingresar");

        javax.swing.GroupLayout btnStaffLoginLayout = new javax.swing.GroupLayout(btnStaffLogin);
        btnStaffLogin.setLayout(btnStaffLoginLayout);
        btnStaffLoginLayout.setHorizontalGroup(
            btnStaffLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStaffLoginLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblStaffLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        btnStaffLoginLayout.setVerticalGroup(
            btnStaffLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStaffLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        txtStaffPassword.setBackground(new java.awt.Color(241, 211, 142));
        txtStaffPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtStaffPassword.setForeground(new java.awt.Color(46, 61, 79));
        txtStaffPassword.setText("jPasswordField1");
        txtStaffPassword.setBorder(null);
        txtStaffPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStaffPasswordFocusGained(evt);
            }
        });

        lblStaffPassword.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblStaffPassword.setForeground(new java.awt.Color(46, 61, 79));
        lblStaffPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStaffPassword.setText("<html>\nContraseña\n<br>\nde    Acceso\n");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnStaffLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblStaffIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblStaffIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStaffPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)))
                .addComponent(btnStaffLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        customerPanel.setBackground(new java.awt.Color(238, 235, 193));

        lblCustomerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer_icon.png"))); // NOI18N

        lblCustomer.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(46, 61, 79));
        lblCustomer.setText("Clientes");

        btnMakeOrder.setBackground(new java.awt.Color(238, 235, 193));
        btnMakeOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 60, 44), 3));
        btnMakeOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMakeOrder.addMouseListener(new MainClickEvent(this));

        lblMakeOrder.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblMakeOrder.setForeground(new java.awt.Color(220, 60, 44));
        lblMakeOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMakeOrder.setText("Odenar");

        javax.swing.GroupLayout btnMakeOrderLayout = new javax.swing.GroupLayout(btnMakeOrder);
        btnMakeOrder.setLayout(btnMakeOrderLayout);
        btnMakeOrderLayout.setHorizontalGroup(
            btnMakeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMakeOrderLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(lblMakeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        btnMakeOrderLayout.setVerticalGroup(
            btnMakeOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMakeOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblExit.setForeground(new java.awt.Color(220, 60, 44));
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        txtCustomerName.setBackground(new java.awt.Color(238, 235, 193));
        txtCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txtCustomerName.setForeground(new java.awt.Color(46, 61, 79));
        txtCustomerName.setBorder(null);
        txtCustomerName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerNameFocusGained(evt);
            }
        });

        txtCustomerId.setBackground(new java.awt.Color(238, 235, 193));
        txtCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        txtCustomerId.setForeground(new java.awt.Color(46, 61, 79));
        txtCustomerId.setBorder(null);
        txtCustomerId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCustomerIdFocusGained(evt);
            }
        });
        txtCustomerId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerIdKeyTyped(evt);
            }
        });

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(46, 61, 79));
        lblCustomerName.setText("Nombre");

        lblCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomerId.setForeground(new java.awt.Color(46, 61, 79));
        lblCustomerId.setText("No. de Identificación");

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCustomerIcon)
                .addGap(53, 53, 53)
                .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerId)
                            .addComponent(lblCustomerName)
                            .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerPanelLayout.createSequentialGroup()
                        .addComponent(btnMakeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblExit))
                .addGap(33, 33, 33)
                .addGroup(customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addComponent(lblCustomerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE))
                    .addGroup(customerPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblCustomerId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCustomerName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addComponent(btnMakeOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(adminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_lblExitMouseClicked

    private void txtCustomerIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerIdFocusGained
        txtCustomerId.setText("");
    }//GEN-LAST:event_txtCustomerIdFocusGained

    private void txtCustomerNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCustomerNameFocusGained
        txtCustomerName.setText("");
    }//GEN-LAST:event_txtCustomerNameFocusGained

    private void txtStaffPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStaffPasswordFocusGained
        txtStaffPassword.setText("");
    }//GEN-LAST:event_txtStaffPasswordFocusGained

    private void txtCustomerIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerIdKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtCustomerIdKeyTyped

    public JPanel getBtnMakeOrder() {
        return btnMakeOrder;
    }

    public JTextField getTxtCustomerId() {
        return txtCustomerId;
    }

    public JTextField getTxtCustomerName() {
        return txtCustomerName;
    }

    public JPanel getBtnStaffLogin() {
        return btnStaffLogin;
    }

    public JPasswordField getTxtStaffPassword() {
        return txtStaffPassword;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JPanel btnMakeOrder;
    private javax.swing.JPanel btnStaffLogin;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblCustomerIcon;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMakeOrder;
    private javax.swing.JLabel lblStaffIcon;
    private javax.swing.JLabel lblStaffLogin;
    private javax.swing.JLabel lblStaffPassword;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JPasswordField txtStaffPassword;
    // End of variables declaration//GEN-END:variables
}
