package views;

import controllers.*;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.OrderModel;

/**
 *
 * @author tomas
 */
public class StaffWindow extends javax.swing.JFrame {

    private InitialData initialData = new InitialData();
    
    /**
     * Creates new form StaffWindow
     */
    public StaffWindow() {
        initComponents();
        addMenuItemPanel.setVisible(false);
        viewOrdersPanel.setVisible(false);
        
        cbxMenus.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        sideBtnCreateMenu = new javax.swing.JLabel();
        sideBtnViewOrders = new javax.swing.JLabel();
        sideBtnAddMenuItem = new javax.swing.JLabel();
        lblSidePanelHeader = new javax.swing.JLabel();
        lblStaffIcon = new javax.swing.JLabel();
        viewOrdersPanel = new javax.swing.JPanel();
        lblOrders = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        lblCustomerId = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        lblOrderItems = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblOrderPrice = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblOrderItems = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        createMenuPanel = new javax.swing.JPanel();
        lblCreateMenu = new javax.swing.JLabel();
        lblCreateMenuIcon = new javax.swing.JLabel();
        btnCreateMenu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMenuName = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        addMenuItemPanel = new javax.swing.JPanel();
        lblCreateMenu1 = new javax.swing.JLabel();
        btnAddMenuItem = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        cbxMenus = new javax.swing.JComboBox<>();
        lblItemName = new javax.swing.JLabel();
        lblSelectMenu = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        lblItemDescription = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtItemDescription = new javax.swing.JTextArea();
        lblItemPrice = new javax.swing.JLabel();
        lblAddMenuItemIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante");
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/images/icon.png"));

        sidePanel.setBackground(new java.awt.Color(46, 61, 79));

        sideBtnCreateMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sideBtnCreateMenu.setForeground(new java.awt.Color(255, 255, 255));
        sideBtnCreateMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtnCreateMenu.setText("Crear Menú");
        sideBtnCreateMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        sideBtnCreateMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtnCreateMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtnCreateMenuMouseClicked(evt);
            }
        });

        sideBtnViewOrders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sideBtnViewOrders.setForeground(new java.awt.Color(255, 255, 255));
        sideBtnViewOrders.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtnViewOrders.setText("Ver Ordenes");
        sideBtnViewOrders.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        sideBtnViewOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtnViewOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtnViewOrdersMouseClicked(evt);
            }
        });

        sideBtnAddMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sideBtnAddMenuItem.setForeground(new java.awt.Color(255, 255, 255));
        sideBtnAddMenuItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sideBtnAddMenuItem.setText("<html> Agregar Elemento  a Menú <br>");
        sideBtnAddMenuItem.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray));
        sideBtnAddMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideBtnAddMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideBtnAddMenuItemMouseClicked(evt);
            }
        });

        lblSidePanelHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSidePanelHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblSidePanelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSidePanelHeader.setText("Panel Administración");
        lblSidePanelHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblStaffIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staff_panel_icon.png"))); // NOI18N

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sideBtnCreateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidePanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblStaffIcon)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSidePanelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sideBtnAddMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sideBtnViewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblSidePanelHeader)
                .addGap(18, 18, 18)
                .addComponent(lblStaffIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(sideBtnCreateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(sideBtnAddMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(sideBtnViewOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        viewOrdersPanel.setBackground(new java.awt.Color(238, 235, 193));

        lblOrders.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblOrders.setForeground(new java.awt.Color(46, 61, 79));
        lblOrders.setText("Ordenes");

        tblOrders.setBackground(new java.awt.Color(238, 235, 193));
        tblOrders.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. de Orden", "No. de Identidicación", "Nombre", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrders.setOpaque(false);
        tblOrders.setRowHeight(40);
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        lblCustomerId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomerId.setForeground(new java.awt.Color(46, 61, 79));

        lblOrderId.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblOrderId.setForeground(new java.awt.Color(46, 61, 79));

        lblOrderItems.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOrderItems.setForeground(new java.awt.Color(46, 61, 79));
        lblOrderItems.setText("Elementos de la orden");

        lblCustomerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(46, 61, 79));

        lblOrderPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblOrderPrice.setForeground(new java.awt.Color(46, 61, 79));

        tblOrderItems.setBackground(new java.awt.Color(238, 235, 193));
        tblOrderItems.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblOrderItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrderItems.setOpaque(false);
        tblOrderItems.setRowHeight(40);
        jScrollPane5.setViewportView(tblOrderItems);

        javax.swing.GroupLayout viewOrdersPanelLayout = new javax.swing.GroupLayout(viewOrdersPanel);
        viewOrdersPanel.setLayout(viewOrdersPanelLayout);
        viewOrdersPanelLayout.setHorizontalGroup(
            viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewOrdersPanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblOrderItems, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                                .addGap(259, 259, 259)
                                .addComponent(lblOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                                    .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                                            .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblOrderPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        viewOrdersPanelLayout.setVerticalGroup(
            viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrderItems, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustomerId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrderPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        createMenuPanel.setBackground(new java.awt.Color(238, 235, 193));

        lblCreateMenu.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblCreateMenu.setForeground(new java.awt.Color(46, 61, 79));
        lblCreateMenu.setText("Crear Menú");

        lblCreateMenuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/create_menu.png"))); // NOI18N

        btnCreateMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCreateMenu.setForeground(new java.awt.Color(46, 61, 79));
        btnCreateMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCreateMenu.setText("Crear Menú");
        btnCreateMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 61, 79), 3, true));
        btnCreateMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateMenu.addMouseListener(new StaffClickEvent(this));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(46, 61, 79));
        jLabel6.setText("Ingrese el nombre del menú");

        txtMenuName.setBackground(new java.awt.Color(238, 235, 193));
        txtMenuName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMenuName.setForeground(new java.awt.Color(235, 116, 52));
        txtMenuName.setText("Nombre del menú");
        txtMenuName.setBorder(null);
        txtMenuName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMenuNameFocusGained(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(46, 61, 79));
        jSeparator4.setForeground(new java.awt.Color(46, 61, 79));

        javax.swing.GroupLayout createMenuPanelLayout = new javax.swing.GroupLayout(createMenuPanel);
        createMenuPanel.setLayout(createMenuPanelLayout);
        createMenuPanelLayout.setHorizontalGroup(
            createMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createMenuPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCreateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
            .addGroup(createMenuPanelLayout.createSequentialGroup()
                .addGroup(createMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createMenuPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblCreateMenuIcon)
                        .addGroup(createMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createMenuPanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(createMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createMenuPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(createMenuPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(txtMenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(createMenuPanelLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(lblCreateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        createMenuPanelLayout.setVerticalGroup(
            createMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createMenuPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblCreateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(createMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createMenuPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblCreateMenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createMenuPanelLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtMenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCreateMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        addMenuItemPanel.setBackground(new java.awt.Color(238, 235, 193));

        lblCreateMenu1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblCreateMenu1.setForeground(new java.awt.Color(46, 61, 79));
        lblCreateMenu1.setText("Agregar Elemento a Menú");

        btnAddMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAddMenuItem.setForeground(new java.awt.Color(46, 61, 79));
        btnAddMenuItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAddMenuItem.setText("Agregar Elemento");
        btnAddMenuItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(46, 61, 79), 3, true));
        btnAddMenuItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddMenuItem.addMouseListener(new StaffClickEvent(this));

        txtItemPrice.setBackground(new java.awt.Color(238, 235, 193));
        txtItemPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtItemPrice.setForeground(new java.awt.Color(235, 116, 52));
        txtItemPrice.setBorder(null);
        txtItemPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtItemPriceKeyTyped(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(46, 61, 79));
        jSeparator5.setForeground(new java.awt.Color(46, 61, 79));

        cbxMenus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxMenus.setModel(new DefaultComboBoxModel(initialData.getMenus().toArray()));

        lblItemName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblItemName.setForeground(new java.awt.Color(46, 61, 79));
        lblItemName.setText("Nombre del Elemento");

        lblSelectMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSelectMenu.setForeground(new java.awt.Color(46, 61, 79));
        lblSelectMenu.setText("Selección Menú");

        txtItemName.setBackground(new java.awt.Color(238, 235, 193));
        txtItemName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtItemName.setForeground(new java.awt.Color(235, 116, 52));
        txtItemName.setBorder(null);

        jSeparator6.setBackground(new java.awt.Color(46, 61, 79));
        jSeparator6.setForeground(new java.awt.Color(46, 61, 79));

        lblItemDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblItemDescription.setForeground(new java.awt.Color(46, 61, 79));
        lblItemDescription.setText("Descripción");

        jScrollPane2.setBorder(null);

        txtItemDescription.setBackground(new java.awt.Color(238, 235, 193));
        txtItemDescription.setColumns(20);
        txtItemDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtItemDescription.setForeground(new java.awt.Color(235, 116, 52));
        txtItemDescription.setRows(5);
        txtItemDescription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 61, 79), 2));
        jScrollPane2.setViewportView(txtItemDescription);

        lblItemPrice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblItemPrice.setForeground(new java.awt.Color(46, 61, 79));
        lblItemPrice.setText("Precio");

        lblAddMenuItemIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_menu_item.png"))); // NOI18N

        javax.swing.GroupLayout addMenuItemPanelLayout = new javax.swing.GroupLayout(addMenuItemPanel);
        addMenuItemPanel.setLayout(addMenuItemPanelLayout);
        addMenuItemPanelLayout.setHorizontalGroup(
            addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblCreateMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMenuItemPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemName)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSelectMenu)
                            .addComponent(cbxMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAddMenuItemIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addMenuItemPanelLayout.createSequentialGroup()
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73))))
                        .addGap(36, 36, 36))
                    .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblItemDescription)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addMenuItemPanelLayout.setVerticalGroup(
            addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreateMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblItemDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)
                        .addGap(19, 19, 19))
                    .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblAddMenuItemIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(addMenuItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                        .addComponent(lblItemPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnAddMenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(addMenuItemPanelLayout.createSequentialGroup()
                        .addComponent(lblSelectMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(viewOrdersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(217, 217, 217)
                    .addComponent(createMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(227, 227, 227)
                    .addComponent(addMenuItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewOrdersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(createMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(addMenuItemPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        int selectedRow = tblOrders.getSelectedRow();
        OrderModel order = initialData.getOrders().get(selectedRow);
        
        lblOrderId.setText( "Orden No. " + String.valueOf(order.getId()) );
        lblCustomerId.setText(order.getCustomerId());
        lblCustomerName.setText(order.getCustomerName());
        lblOrderPrice.setText( "$ " + String.valueOf(order.getTotalPrice()) );
        
        String[] headers = {"Nombre", "Precio"};
        tblOrderItems.removeAll();

        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers); 
        tblOrderItems.setModel(tableModel);

        order.getItems().forEach((item)->{
            tableModel.addRow(item.toArray());
        });
    }//GEN-LAST:event_tblOrdersMouseClicked

    private void sideBtnViewOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtnViewOrdersMouseClicked
        createMenuPanel.setVisible(false);
        addMenuItemPanel.setVisible(false);
        viewOrdersPanel.setVisible(true);
        setTblOrders();
    }//GEN-LAST:event_sideBtnViewOrdersMouseClicked

    private void sideBtnCreateMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtnCreateMenuMouseClicked
        viewOrdersPanel.setVisible(false);
        addMenuItemPanel.setVisible(false);
        createMenuPanel.setVisible(true);
    }//GEN-LAST:event_sideBtnCreateMenuMouseClicked

    private void txtMenuNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMenuNameFocusGained
        txtMenuName.setText("");
    }//GEN-LAST:event_txtMenuNameFocusGained

    private void txtItemPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemPriceKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c))
            evt.consume();
    }//GEN-LAST:event_txtItemPriceKeyTyped

    private void sideBtnAddMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideBtnAddMenuItemMouseClicked
        createMenuPanel.setVisible(false);
        viewOrdersPanel.setVisible(false);
        addMenuItemPanel.setVisible(true);
        setCbxMenus();
    }//GEN-LAST:event_sideBtnAddMenuItemMouseClicked

    public void setTblOrders() {
        String[] headers = {"No. Orden", "No. Identificación", "Nombre Cliente", "Valor Total"};
        tblOrders.removeAll();
        
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers); 
        tblOrders.setModel(tableModel);
        
        initialData.getOrders().forEach((order) -> {
            tableModel.addRow(order.toArray());
        }); 
    }
    
    private void setCbxMenus(){
        cbxMenus.setModel(new DefaultComboBoxModel(new InitialData().getMenus().toArray()));
    }

    public JLabel getBtnCreateMenu() {
        return btnCreateMenu;
    }

    public JTextField getTxtMenuName() {
        return txtMenuName;
    }

    public JLabel getBtnAddMenuItem() {
        return btnAddMenuItem;
    }

    public JTextArea getTxtItemDescription() {
        return txtItemDescription;
    }

    public JTextField getTxtItemName() {
        return txtItemName;
    }

    public JTextField getTxtItemPrice() {
        return txtItemPrice;
    }

    public JComboBox<String> getCbxMenus() {
        return cbxMenus;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addMenuItemPanel;
    private javax.swing.JLabel btnAddMenuItem;
    private javax.swing.JLabel btnCreateMenu;
    private javax.swing.JComboBox<String> cbxMenus;
    private javax.swing.JPanel createMenuPanel;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblAddMenuItemIcon;
    private javax.swing.JLabel lblCreateMenu;
    private javax.swing.JLabel lblCreateMenu1;
    private javax.swing.JLabel lblCreateMenuIcon;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblItemDescription;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemPrice;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblOrderItems;
    private javax.swing.JLabel lblOrderPrice;
    private javax.swing.JLabel lblOrders;
    private javax.swing.JLabel lblSelectMenu;
    private javax.swing.JLabel lblSidePanelHeader;
    private javax.swing.JLabel lblStaffIcon;
    private javax.swing.JLabel sideBtnAddMenuItem;
    private javax.swing.JLabel sideBtnCreateMenu;
    private javax.swing.JLabel sideBtnViewOrders;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tblOrderItems;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextArea txtItemDescription;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtMenuName;
    private javax.swing.JPanel viewOrdersPanel;
    // End of variables declaration//GEN-END:variables
}
